### PR TITLE
Add moorepants as a maintainer.

### PR DESCRIPTION
**Pull request by moorepants**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by moorepants** [comment]
I maintain a number of other dash feedstocks and now that dash table is a hard dependency for dash, it'd be helpful if I could merge updates here.

**Comment by moorepants** [comment]
@conda-forge/dash-table Would you mind if I am a co-maintainer?

**Comment by moorepants** [comment]
@conda-forge/help-python Hi conda forge devs. There has been no activity from @dkucharc since Jan 3, 2019 in this repository. I maintain most of the other dash related feedstocks and this one is now a dependency for dash. It is a bottle neck for the work I do with the other feedstocks. Can I be made a maintainer of this feedstock?

**Comment by beckermr** [comment]
You need to ping @conda-forge/core to get them to merge this PR.

**Comment by CJ-Wright** [comment]
Thank you very much for volunteering @moorepants !

**Pull request merged**
